install.packages("shiny")
install.packages("shinyjs")
install.packages("shinythemes")
install.packages("rio")
install.packages("tidyverse")
install.packages("ggrepel")
install.packages("stringr")
install.packages("lubridate")
install.packages("tidyr")
install.packages("magrittr")
install.packages("bit64")
install.packages("plotly")

